### ISSUE TITLE
Looking for wrong user profile directory

### ISSUE THREAD

**Issue by tjdownes** [EliteAPI/EliteHook#2]
On startup, I receive the error `Error: The directory name C:\Users\AWrongUsername\Saved Games\Frontier`

I have no idea why it would be searching for that directory unless the code is using the username instead of the profile path to look it up.

In my case, my user folder is `username.domain`, and therefore the path is not found,

**Comment by Somfic** [comment]
Hello, are you using the .NET library, the VoiceAttack plugin or the VoiceMacro part of EliteAPI?

**Comment by Somfic** [comment]
Hi, first of all my apologies that you're running into issues. 

EliteHook by default uses the user's username to look up the Journal Folder. I've added a customization file in [release v1.0.0.1](https://github.com/EliteAPI/EliteHook/releases/tag/v1.0.0.1) which should take care of the problem. Due to some people having limited access in their Programs Files folder, I recommend using the installer's default installation location as well and removing the old install in Program Files. 

Copy past the Journal Folder location in the EliteHook.ini file (which will be created after running EliteHook at least once). Usually, your Journal Folder is located in `C:\Users\%username%\Saved Games\Frontier Developments\Elite Dangerous`.

If you're running into more issues or need further help, please do not hesitate the contact me!

Thanks, 
Somfic.

**Comment by tjdownes** [comment]
Thanks for the quick response. I removed the old version (which I installed from http://edcodex.info/?m=tools&entry=471) and reinstalled your new release tag.

The install path is now `C:\Users\%username%\AppData\Roaming\EliteHook` and receiving the same error. I am looking for the EliteHook.ini file and not seeing it in that location. I've run the exe a few times.

**Comment by Somfic** [comment]
Try copy pasting the path `C:\Users\%appdata%\AppData\Roaming\EliteHook\EliteHook.ini` in your File Explorer. It should be there after running EliteHook.

**Comment by tjdownes** [comment]
![image](https://user-images.githubusercontent.com/273720/53978576-6a21a880-40c0-11e9-9bf1-4a279831a11f.png)

**Comment by Somfic** [comment]
That's very odd, and implies the issue lays before the initialization of the API. Could you also give me a screenshot of the error screen?

**Comment by tjdownes** [comment]
![image](https://user-images.githubusercontent.com/273720/53978774-e4522d00-40c0-11e9-988b-6de491436183.png)

(Your code is showing up in the window's transparency because I am looking through it on GH ;))

**Comment by Somfic** [comment]
I was able to recreate the error. Please try [this](https://github.com/EliteAPI/EliteHook/releases/tag/p1.0.0.3) patch (remove every file in old installation and paste it there).

**Comment by tjdownes** [comment]
![image](https://user-images.githubusercontent.com/273720/53979957-f97c8b00-40c3-11e9-8ae3-33614a7b0b4b.png)


I'm not really comfortable installing this version.

**Comment by Somfic** [comment]
I did not create an installer for it this time, which might be the cause of the false-positive. I'll make an installer for it.

**Comment by Somfic** [comment]
1.0.0.2 can be found in the [releases tab](https://github.com/EliteAPI/EliteHook/releases).

**Comment by tjdownes** [comment]
That version installed fine, thanks!

After editing the .ini file, I still receive the same error (with the same incorrect path).

Just FYI, if I copy that `Saved Games/Frontier Developments` folder to the path it's looking for, everything loads. So it's only a path issue. Not a fix or workaround, because the path won't be updated by ED, but just an FYI that everything else seems OK.

**Comment by Somfic** [comment]
Are you sure you have the .ini file and that the path you put in is the actual Elite Dangerous folder? I replaced & removed my Elite Dangerous directory to recreate your error and after updating the .ini everything loads up like usual

**Comment by tjdownes** [comment]
I had a lot of bourbon last night, so maybe I'm not seeing it :)

![image](https://user-images.githubusercontent.com/273720/53980782-0e5a1e00-40c6-11e9-9102-31270ff86d5f.png)

**Comment by Somfic** [comment]
Hahah, oh yes, with 1.0.0.2 the support files are no longer needed and cause an exception. You're free to remove every file except EliteHook.exe, EliteHook.exe.config, EliteHook.pdb, and EliteHook.ini

**Comment by tjdownes** [comment]
Well there you go, everything fires right up. Thanks!

**Comment by Somfic** [comment]
Most happy to hear that. Sorry it took 12 thousand messages, hahah. Thanks!

**Comment by tjdownes** [comment]
no worries. I wish i knew MS APIs and C# a little better so I could be more help. A thousand thanks.
